INSERT INTO SYNC.NOTICE
(NOTICE_SEQ, NOTICE_TITLE, NOTICE_CONTENT, NOTICE_REGDATE, NOTICE_DELFLAG, NOTICE_PINBTN, EMP_ID)
VALUES((SELECT NVL(MAX(NOTICE_SEQ),0)+1 FROM NOTICE) , '공지에요3', '안녕하세요', CURRENT_DATE, 'N'	, 'N'	, 'A002');


SELECT COUNT(*)
FROM NOTICE n 