


SELECT *
	FROM EMPLOYEE e JOIN TEAM t 
	ON e.TEAM_CODE = t.TEAM_CODE 
	JOIN DIVISION d 
	ON t.UPSTAIRS_DIVISION_CODE  = d.DIVISION_CODE;
	


INSERT INTO RANK (RANK_ID, RANK_NAME) VALUES ('RANK001','대표이사');
INSERT INTO RANK (RANK_ID, RANK_NAME) VALUES ('RANK002','사장');
INSERT INTO RANK (RANK_ID, RANK_NAME) VALUES ('RANK003','부장');
INSERT INTO RANK (RANK_ID, RANK_NAME) VALUES ('RANK004','과장');
INSERT INTO RANK (RANK_ID, RANK_NAME) VALUES ('RANK005','대리');
INSERT INTO RANK (RANK_ID, RANK_NAME) VALUES ('RANK006','사원');