SELECT * FROM (
    SELECT 
        NOTICE_SEQ, 
        NOTICE_TITLE, 
        DBMS_LOB.SUBSTR(NOTICE_CONTENT, 4000, 1) AS NOTICE_CONTENT,  
        NOTICE_REGDATE, 
        NOTICE_DELFLAG, 
        NOTICE_PINBTN,
        EMP_ID,
        ROW_NUMBER() OVER (ORDER BY NOTICE_PINBTN DESC , NOTICE_SEQ DESC ) AS RN
    FROM NOTICE
) WHERE RN BETWEEN 1 AND 5



SELECT COUNT(*)
FROM NOTICE n 
WHERE NOTICE_DELFLAG = 'N'

INSERT INTO SYNC.NOTICE (
    NOTICE_SEQ,
    NOTICE_TITLE,
    NOTICE_CONTENT,
    NOTICE_REGDATE,
    NOTICE_DELFLAG,
    NOTICE_PINBTN,
    EMP_ID
)
SELECT 
    NVL(MAX(NOTICE_SEQ), 0) + 1 AS NEW_SEQ,
    '공지에요' || (NVL(MAX(NOTICE_SEQ), 0) + 1) AS NEW_TITLE,
    '안녕하세요' || (NVL(MAX(NOTICE_SEQ), 0) + 1) AS NEW_CONTENT,
    CURRENT_DATE AS NOTICE_REGDATE,
    'N' AS NOTICE_DELFLAG,
    'N' AS NOTICE_PINBTN,
    'A002' AS EMP_ID
FROM 
    SYNC.NOTICE;
    
   
SELECT *
FROM NOTICE n 




UPDATE NOTICE SET NOTICE_DELFLAG = 'Y'
WHERE NOTICE_DELFLAG ='N'
AND NOTICE_SEQ  =  1


SELECT NOTICE_SEQ, NOTICE_TITLE, NOTICE_CONTENT, 
TO_CHAR(NOTICE_REGDATE, 'YYYY/MM/DD HH:mi:ss')NOTICE_REGDATE, 
NOTICE_DELFLAG, NOTICE_PINBTN, EMP_ID 
FROM NOTICE n 
WHERE NOTICE_SEQ = '16'


UPDATE NOTICE SET NOTICE_CONTENT = '공지사항1 수정했습니다'
WHERE NOTICE_SEQ = '1'

UPDATE NOTICE  SET NOTICE_PINBTN = 'Y'
WHERE NOTICE_SEQ = '15'


UPDATE NOTICE
SET NOTICE_PINBTN = 'N'
WHERE NOTICE_SEQ = '3'


SELECT COUNT(*) FROM NOTICE WHERE NOTICE_PINBTN = 'Y'

SELECT *
FROM NOTICE n 
WHERE NOTICE_PINBTN = 'Y'

EMP_ID LIKE '%'||1||'%'

SELECT EMP_ID, NOTICE_TITLE 
		FROM NOTICE n  
		WHERE  NOTICE_DELFLAG = 'N'
		AND NOTICE_TITLE LIKE '%'||'집'||'%'



INSERT INTO NOTICE
(NOTICE_SEQ, NOTICE_TITLE, NOTICE_CONTENT, 
NOTICE_REGDATE, NOTICE_DELFLAG, NOTICE_PINBTN, 
EMP_ID)
VALUES((SELECT NVL(MAX(NOTICE_SEQ),0)+1 FROM NOTICE n ), '피카츄', '백만볼트', CURRENT_DATE ,'N', 'N', 'A001');




